variable practice

diff --git a/09-installation b/09-installation
--- a/09-installation
+++ b/09-installation
@@ -1,40 +1,38 @@
 #!/bin/bash
+
 USERID=$(id -u)
-#echo "User id is: $USERID"
-if [ $USERID -ne 0 ]
-then
-    echo "Please run this script with root priveleges"
-    exit 1
 
+if [ "$USERID" -ne 0 ]; then
+    echo "Please run this script with root privileges"
+    exit 1
 fi
-dnf list install git 
-if [ $? -ne 0 ]
-then
-    echo "Git is not installed , got install it..."
+
+# Check if Git is installed
+dnf list installed git &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "Git is not installed. Installing..."
     dnf install git -y
-    if [ $? -ne 0]
-then
-    echo "git not install sucess , check it command"
-    exit 1
+    if [ $? -ne 0 ]; then
+        echo "Git installation failed. Please check the command."
+        exit 1
+    else
+        echo "Git installed successfully."
+    fi
 else
-    echo "git install is success "
-
-else
-    echo "git already installed , nothign to do"
+    echo "Git is already installed. Nothing to do."
 fi
 
-dnf list install mysql -y
-if [ $? -ne 0 ]
-then
-    echo "mysql not installed going to install"
+# Check if MySQL is installed
+dnf list installed mysql &>/dev/null
+if [ $? -ne 0 ]; then
+    echo "MySQL is not installed. Installing..."
     dnf install mysql -y
-    if [ $? -ne 0 ]
-    then
-        echo "mysql installation is files and check"
+    if [ $? -ne 0 ]; then
+        echo "MySQL installation failed. Please check."
         exit 1
-    else 
-        echo "mysql is sucess"
+    else
+        echo "MySQL installed successfully."
     fi
-else 
-    echo "mysql already installed"
-fi    
+else
+    echo "MySQL is already installed. Nothing to do."
+fi
